<?php

namespace AppBundle\Repository;

/**
 * ChoicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChoicesRepository extends \Doctrine\ORM\EntityRepository
{
}
