<?php

namespace AppBundle\Repository;

/**
 * GamesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GamesRepository extends \Doctrine\ORM\EntityRepository
{
}
